In [1]:
# Include libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
# DATA COLLECTION
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Input split
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]

In [6]:
# Output split
dependent=dataset[['charges']]

In [7]:
# Standardization
# Preprocessing Input data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
independent=sc.fit_transform(independent)

In [8]:
# Preprocessing Output data
scy=StandardScaler()
dependent=scy.fit_transform(dependent)

In [9]:
# Model creation using gridserch
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'C': [ 10, 100, 1000, 2000, 3000],
			  'gamma': ['auto','scale'], 
			  'kernel': ['rbf','linear', 'sigmoid']} 
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3, n_jobs = -1) 
grid.fit(independent, dependent) 

Fitting 5 folds for each of 30 candidates, totalling 150 fits


/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'linear', 'sigmoid']},
             verbose=3)

In [10]:
# Output predict
y_pred=grid.predict(independent)
from sklearn.metrics import r2_score
r_score=r2_score(y_pred,dependent)

In [11]:
# Print best parameter after tuning
re=grid.cv_results_
print("R_score value for best parameter{}:".format(grid.best_params_), r_score)

R_score value for best parameter{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}: 0.8390303778370944


In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0        0.086408      0.016730         0.005617        0.002858       10   
1        0.254965      0.018124         0.001082        0.000016       10   
2        0.050066      0.001982         0.007772        0.003224       10   
3        0.082349      0.004796         0.004577        0.002770       10   
4        0.255092      0.027028         0.001050        0.000028       10   
5        0.053363      0.009881         0.004823        0.000203       10   
6        0.389736      0.063729         0.003337        0.000093      100   
7        1.917984      0.056363         0.002391        0.001069      100   
8        0.053174      0.005474         0.006716        0.002061      100   
9        0.390580      0.057130         0.007339        0.002755      100   
10       1.925022      0.065922         0.001269        0.000388      100   
11       0.050877      0.001761         0.006959        0.002076      100   
12       2.852763      0.579336         0.006687        0.003041     1000   
13      18.419460      1.739902         0.002207        0.001200     1000   
14       0.054047      0.001366         0.004745        0.000146     1000   
15       2.966598      0.701082         0.005050        0.001486     1000   
16      19.328159      1.499555         0.001928        0.000778     1000   
17       0.063433      0.006741         0.006928        0.002333     1000   
18       6.176620      0.505080         0.004812        0.000682     2000   
19      44.565567      1.894635         0.001540        0.000222     2000   
20       0.064700      0.004231         0.007897        0.002795     2000   
21       6.603599      0.570123         0.007612        0.002764     2000   
22      45.985081      2.159343         0.002431        0.000846     2000   
23       0.070786      0.009080         0.008297        0.002232     2000   
24      11.487998      1.145418         0.006641        0.001715     3000   
25      71.392037      5.116544         0.002540        0.001057     3000   
26       0.061642      0.002806         0.008577        0.001875     3000   
27      11.556290      1.675257         0.006459        0.001406     3000   
28      60.658736      7.296539         0.001367        0.000134     3000   
29       0.072129      0.005719         0.010657        0.003238     3000   

   param_gamma param_kernel  \
0         auto          rbf   
1         auto       linear   
2         auto      sigmoid   
3        scale          rbf   
4        scale       linear   
5        scale      sigmoid   
6         auto          rbf   
7         auto       linear   
8         auto      sigmoid   
9        scale          rbf   
10       scale       linear   
11       scale      sigmoid   
12        auto          rbf   
13        auto       linear   
14        auto      sigmoid   
15       scale          rbf   
16       scale       linear   
17       scale      sigmoid   
18        auto          rbf   
19        auto       linear   
20        auto      sigmoid   
21       scale          rbf   
22       scale       linear   
23       scale      sigmoid   
24        auto          rbf   
25        auto       linear   
26        auto      sigmoid   
27       scale          rbf   
28       scale       linear   
29       scale      sigmoid   

                                               params  split0_test_score  \
0         {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}       8.774542e-01   
1      {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}       6.917471e-01   
2     {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}      -7.207321e+03   
3        {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}       8.774248e-01   
4     {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}       6.917471e-01   
5    {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}      -6.535274e+03   
6        {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}       8.561973e-01   
7     {'C': 100, 'gamma': 'auto', 'kernel': 'l

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 23
Children: 1
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1


In [15]:
# Here we get preprocessed output
Future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(Future_prediction))

Future_prediction=[0.50834589]


In [16]:
# SAVE THE MODEL
import pickle
filename="Finalized_model-SVM-Grid-preprocess_input&output.sav"

In [17]:
pickle.dump(grid,open(filename,'wb'))

In [18]:
# Input preprocessing
preinput=sc.transform([[32,23,1,1,1]])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [19]:
preinput

array([[-0.51314879, -1.25713795, -0.07876719,  0.98959079,  1.97058663]])

In [20]:
loaded_model = pickle.load(open("Finalized_model-SVM-Grid-preprocess_input&output.sav", 'rb'))
result = loaded_model.predict(preinput)

In [21]:
result

array([-0.00034067])

In [22]:
preoutput=scy.inverse_transform([result])

In [48]:
preoutput

array([[13266.2982996]])