In [1]:
# Include libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
# DATA COLLECTION
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Input split
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]

In [6]:
# Output split
dependent=dataset[['charges']]

In [7]:
# Standardization
# Preprocessing Input data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
independent=sc.fit_transform(independent)

In [8]:
# Preprocessing Output data
scy=StandardScaler()
dependent=scy.fit_transform(dependent)

In [9]:
# Model creation using gridserch
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'C': [ 10, 100, 1000, 2000, 3000],
			  'gamma': ['auto','scale'], 
			  'kernel': ['rbf']} 
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3, n_jobs = -1) 
grid.fit(independent, dependent) 

Fitting 5 folds for each of 10 candidates, totalling 50 fits


/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'], 'kernel': ['rbf']},
             verbose=3)

In [10]:
# Output predict
y_pred=grid.predict(independent)
from sklearn.metrics import r2_score
r_score=r2_score(y_pred,dependent)

In [11]:
# Print best parameter after tuning
re=grid.cv_results_
print("R_score value for best parameter{}:".format(grid.best_params_), r_score)

R_score value for best parameter{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}: 0.8390303778370944


In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.083931      0.010795         0.004401        0.001457       10   
1       0.082260      0.014171         0.004468        0.001527       10   
2       0.397877      0.052913         0.003660        0.000582      100   
3       0.381640      0.079747         0.003539        0.000343      100   
4       2.871615      0.616566         0.004964        0.002430     1000   
5       2.890713      0.675632         0.004062        0.000796     1000   
6       5.624535      0.427601         0.006217        0.002851     2000   
7       5.795002      0.564300         0.008583        0.003028     2000   
8       9.061337      0.949024         0.006370        0.001729     3000   
9       7.704173      1.180619         0.003854        0.000230     3000   

  param_gamma param_kernel                                          params  \
0        auto          rbf     {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}   
1       scale          rbf    {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}   
2        auto          rbf    {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}   
3       scale          rbf   {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}   
4        auto          rbf   {'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}   
5       scale          rbf  {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}   
6        auto          rbf   {'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}   
7       scale          rbf  {'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}   
8        auto          rbf   {'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}   
9       scale          rbf  {'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.877454           0.796369           0.871761           0.827689   
1           0.877425           0.796427           0.871885           0.827667   
2           0.856197           0.784094           0.864463           0.817223   
3           0.855843           0.784422           0.864383           0.817224   
4           0.820239           0.723377           0.777807           0.744387   
5           0.819382           0.724529           0.780526           0.743412   
6           0.750473           0.691658           0.649473           0.644789   
7           0.746239           0.692859           0.647405           0.643226   
8           0.682761           0.639877           0.555280           0.577418   
9           0.677413           0.642945           0.561032           0.576372   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  
0           0.844697         0.843594        0.029747                2  
1           0.844740         0.843629        0.029748                1  
2           0.836350         0.831665        0.028883                3  
3           0.836288         0.831632        0.028694                4  
4           0.742918         0.761746        0.034081                6  
5           0.741184         0.761807        0.034113                5  
6           0.645103         0.676299        0.041045                7  
7           0.646924         0.675331        0.039881                8  
8           0.613922         0.613852        0.045131               10  
9           0.614604         0.614473        0.042614                9

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 23
Children: 1
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1


In [35]:
# Here we get preprocessed output
Future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(Future_prediction))

Future_prediction=[0.50834589]


In [37]:
# SAVE THE MODEL
import pickle
filename="Finalized_model-SVM-Grid-preprocess_input&output.sav"

In [47]:
pickle.dump(grid,open(filename,'wb'))
filename = 'scy.pkl'
pickle.dump(scy, open(filename, 'wb'))

In [49]:
# Input preprocessing
preinput=sc.transform([[32,23,1,1,1]])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [51]:
preinput

array([[-0.51314879, -1.25713795, -0.07876719,  0.98959079,  1.97058663]])

In [53]:
loaded_model = pickle.load(open("Finalized_model-SVM-Grid-preprocess_input&output.sav", 'rb'))
result = loaded_model.predict(preinput)

In [55]:
result

array([-0.00034067])

In [57]:
preoutput=scy.inverse_transform([result])

In [59]:
preoutput

array([[13266.2982996]])