In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
# DATA COLLECTION
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]

In [6]:
dependent=dataset[['charges']]

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
independent=sc.fit_transform(independent)

In [8]:
independent

array([[-1.43876426, -0.45332   , -0.90861367, -1.0105187 ,  1.97058663],
       [-1.50996545,  0.5096211 , -0.07876719,  0.98959079, -0.5074631 ],
       [-0.79795355,  0.38330685,  1.58092576,  0.98959079, -0.5074631 ],
       ...,
       [-1.50996545,  1.0148781 , -0.90861367, -1.0105187 , -0.5074631 ],
       [-1.29636188, -0.79781341, -0.90861367, -1.0105187 , -0.5074631 ],
       [ 1.55168573, -0.26138796, -0.90861367, -1.0105187 ,  1.97058663]])

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'C': [ 10, 100, 1000, 2000, 3000],
			  'gamma': ['auto','scale'], 
			  'kernel': ['rbf','sigmoid','linear']} 
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3, n_jobs = -1) 
grid.fit(independent,dependent) 

Fitting 5 folds for each of 30 candidates, totalling 150 fits


/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'sigmoid', 'linear']},
             verbose=3)

In [10]:
y_pred=grid.predict(independent)
from sklearn.metrics import r2_score
r_score=r2_score(y_pred,dependent)

In [11]:
# Print best parameter after tuning
re=grid.cv_results_
print("R_score value for best parameter{}:".format(grid.best_params_), r_score)

R_score value for best parameter{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}: 0.8049508453990315


In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0        0.045176      0.013431         0.014285        0.006758       10   
1        0.046649      0.006335         0.010841        0.005314       10   
2        0.027662      0.005539         0.003867        0.002155       10   
3        0.033886      0.007569         0.011861        0.003410       10   
4        0.050816      0.007047         0.007645        0.002741       10   
5        0.034537      0.007446         0.003541        0.001790       10   
6        0.032375      0.006629         0.011473        0.002963      100   
7        0.042242      0.005636         0.009032        0.002658      100   
8        0.032546      0.007744         0.004457        0.002610      100   
9        0.035339      0.005144         0.012398        0.002998      100   
10       0.045407      0.003765         0.005027        0.000140      100   
11       0.031918      0.006090         0.003618        0.002029      100   
12       0.045834      0.011765         0.013083        0.002539     1000   
13       0.048023      0.005309         0.004979        0.000036     1000   
14       0.041417      0.002326         0.003032        0.001269     1000   
15       0.040127      0.005205         0.018252        0.006472     1000   
16       0.047587      0.006059         0.007358        0.002573     1000   
17       0.037801      0.013049         0.003043        0.001394     1000   
18       0.058184      0.007469         0.017366        0.007179     2000   
19       0.047490      0.008432         0.005712        0.001474     2000   
20       0.050840      0.008318         0.002429        0.000241     2000   
21       0.040617      0.003070         0.009549        0.001475     2000   
22       0.048702      0.005268         0.006942        0.001468     2000   
23       0.056252      0.008986         0.004008        0.002085     2000   
24       0.055924      0.005017         0.014087        0.003978     3000   
25       0.051190      0.007575         0.006618        0.002834     3000   
26       0.073805      0.013662         0.003352        0.001701     3000   
27       0.047567      0.005478         0.010651        0.002663     3000   
28       0.053012      0.010360         0.006809        0.002269     3000   
29       0.056183      0.007377         0.004350        0.002594     3000   

   param_gamma param_kernel  \
0         auto          rbf   
1         auto      sigmoid   
2         auto       linear   
3        scale          rbf   
4        scale      sigmoid   
5        scale       linear   
6         auto          rbf   
7         auto      sigmoid   
8         auto       linear   
9        scale          rbf   
10       scale      sigmoid   
11       scale       linear   
12        auto          rbf   
13        auto      sigmoid   
14        auto       linear   
15       scale          rbf   
16       scale      sigmoid   
17       scale       linear   
18        auto          rbf   
19        auto      sigmoid   
20        auto       linear   
21       scale          rbf   
22       scale      sigmoid   
23       scale       linear   
24        auto          rbf   
25        auto      sigmoid   
26        auto       linear   
27       scale          rbf   
28       scale      sigmoid   
29       scale       linear   

                                               params  split0_test_score  \
0         {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}          -0.050402   
1     {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}           0.029301   
2      {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}           0.487873   
3        {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}          -0.050517   
4    {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}           0.029716   
5     {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}           0.487873   
6        {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}           0.360724   
7    {'C': 100, 'gamma': 'auto', 'kernel': 'si

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 23
Children: 1
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1


In [15]:
Future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(Future_prediction))

Future_prediction=[17144.08720329]


In [16]:
# SAVE THE MODEL
import pickle
filename="Finalized_model-SVM-Grid-preprocess_input.sav"

In [17]:
pickle.dump(grid,open(filename,'wb'))

In [18]:
preinput=sc.transform([[32,23,1,1,1]])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [19]:
preinput

array([[-0.51314879, -1.25713795, -0.07876719,  0.98959079,  1.97058663]])

In [20]:
loaded_model = pickle.load(open("Finalized_model-SVM-Grid-preprocess_input.sav", 'rb'))
result = loaded_model.predict(preinput)

In [21]:
result

array([15145.76990933])