In [1]:
# INCLUDE LIBRARIES
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
# DATA COLLECTION
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Input split
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]

In [6]:
# Output split
dependent=dataset[['charges']]

In [7]:
# Standardization
# Preprocessing Input data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
independent=sc.fit_transform(independent)

In [8]:
# Preprocessing Output data
scy=StandardScaler()
dependent=scy.fit_transform(dependent)

In [9]:
# Model creation using gridserch
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'C': [ 10, 100, 1000, 2000, 3000],
			  'gamma': ['auto','scale'], 
			  'kernel': ['rbf']} 
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3, n_jobs = -1) 
grid.fit(independent, dependent) 

Fitting 5 folds for each of 10 candidates, totalling 50 fits


/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'], 'kernel': ['rbf']},
             verbose=3)

In [10]:
# Output predict
y_pred=grid.predict(independent)
from sklearn.metrics import r2_score
r_score=r2_score(y_pred,dependent)

In [11]:
# Print best parameter after tuning
re=grid.cv_results_
print("R_score value for best parameter{}:".format(grid.best_params_), r_score)

R_score value for best parameter{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}: 0.8390303778370944


In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.090474      0.011237         0.005770        0.001939       10   
1       0.083892      0.012740         0.004607        0.001179       10   
2       0.396143      0.058104         0.004470        0.002271      100   
3       0.390728      0.076975         0.005095        0.002458      100   
4       2.916168      0.617986         0.008229        0.002668     1000   
5       2.997389      0.680462         0.005614        0.002614     1000   
6       5.596867      0.389616         0.004702        0.001743     2000   
7       5.655969      0.529877         0.007635        0.003264     2000   
8       9.237752      0.869849         0.005640        0.002703     3000   
9       7.644237      1.280345         0.003798        0.000198     3000   

  param_gamma param_kernel                                          params  \
0        auto          rbf     {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}   
1       scale          rbf    {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}   
2        auto          rbf    {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}   
3       scale          rbf   {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}   
4        auto          rbf   {'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}   
5       scale          rbf  {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}   
6        auto          rbf   {'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}   
7       scale          rbf  {'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}   
8        auto          rbf   {'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}   
9       scale          rbf  {'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.877454           0.796369           0.871761           0.827689   
1           0.877425           0.796427           0.871885           0.827667   
2           0.856197           0.784094           0.864463           0.817223   
3           0.855843           0.784422           0.864383           0.817224   
4           0.820239           0.723377           0.777807           0.744387   
5           0.819382           0.724529           0.780526           0.743412   
6           0.750473           0.691658           0.649473           0.644789   
7           0.746239           0.692859           0.647405           0.643226   
8           0.682761           0.639877           0.555280           0.577418   
9           0.677413           0.642945           0.561032           0.576372   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  
0           0.844697         0.843594        0.029747                2  
1           0.844740         0.843629        0.029748                1  
2           0.836350         0.831665        0.028883                3  
3           0.836288         0.831632        0.028694                4  
4           0.742918         0.761746        0.034081                6  
5           0.741184         0.761807        0.034113                5  
6           0.645103         0.676299        0.041045                7  
7           0.646924         0.675331        0.039881                8  
8           0.613922         0.613852        0.045131               10  
9           0.614604         0.614473        0.042614                9

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 23
Children: 1
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1


In [15]:
# Here we get preprocessed output
Future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(Future_prediction))

Future_prediction=[0.50834589]


In [16]:
# SAVE THE MODEL
import pickle
filename="Finalized_model-SVM-Grid-preprocess1_input&output.sav"

In [18]:
pickle.dump(grid,open(filename,'wb'))
filename_sc = 'sc.pkl'
filename_scy = 'scy.pkl'
pickle.dump(scy, open(filename_scy, 'wb'))
pickle.dump(sc, open(filename_sc, 'wb'))

In [19]:
# Input preprocessing
preinput=sc.transform([[32,23,1,1,1]])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [20]:
preinput

array([[-0.51314879, -1.25713795, -0.07876719,  0.98959079,  1.97058663]])

In [21]:
loaded_model = pickle.load(open("Finalized_model-SVM-Grid-preprocess1_input&output.sav", 'rb'))
result = loaded_model.predict(preinput)

In [22]:
result

array([-0.00034067])

In [23]:
preoutput=scy.inverse_transform([result])

In [24]:
preoutput

array([[13266.2982996]])